/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sampleinput;

/**
 *
 * @author Quang Trung
 */
public class InputData {

    public static String song1 = "Chiều dần buông [C] , anh nghe cơn gió nghẹn [F] ngào\n"
            + "Mặt hồ lung linh [C] hiện lên [Cmaj7] bóng dáng em [F]\n"
            + "Và anh nhớ [G/B] lại phút ban đầu [Am] kề bên nhau [G/B] ánh mắt ngại [F] ngùng \n"
            + "Nhìn nhau [Fm] không nói nên lời [C]\n"
            + "Để rồi [G/B] từng đêm thao thức [Am]\n"
            + "Anh ước mong [Em] một ngày không xa [F]\n"
            + "Cầm chặt tay em [Am]\n"
            + "Đi trên [Em] những giấc mơ dài [F]\n"
            + "Yêu em [E]\n"
            + "Cảm xúc trong anh [A] là em\n"
            + "Tình yêu anh mang [A/F#] là em\n"
            + "Và em có hay [Bm] lời nồng ấm nơi con tim này [D]\n"
            + "Gửi chọn [Dm] tình yêu nơi em [E] \n"
            + "Nguyện ước anh mang [A] là em\n"
            + "Lời ca anh hát [A/F#] là em\n"
            + "Và anh ước mong [Bm]\n"
            + "Sẽ mãi bên em chọn đời [D] dù cho [Dm] phong ba bão tố [E]\n"
            + "Yêu em [A]";
    public static String song2 = "[Em] Trong ------------------------------------------------- cơn mưa đêm nhẹ như gió [D]\n"
            + "Trôi qua không gian và nguôi lãng dần [C] \n"
            + "Những điều [B7] tôi chưa nói với em [Em]\n"
            + "Hôm chia tay cây vừa trút lá [D]\n"
            + "Hôm chia tay ô cửa vẫn sáng đèn [C]\n"
            + "Hát gì lên [B7] đi đêm quá yên\n"
            + "\n"
            + "[Em] Trôi theo cơn mơ bờ sông chói chang [D]\n"
            + "Trôi theo cơn mơ niềm đau rất thật [C]\n"
            + "Có bình yên [B7] nào không xót xa [Em]\n"
            + "Em nơi đây hay còn đâu đó [D]\n"
            + "Cô đơn xa xưa từ giây phút nào.[C] ....... đến vô [B7] cùng\n"
            + "\n"
            + "Bây giờ em biết vì sao [C] gặp nhau [D] biển xô sóng trào [Em]\n"
            + "Ngồi nghe chiều im gió lặng [C] giữa [D] muôn vàn hoa [G]\n"
            + "Đi về đâu cũng là thế,[C] buồn kia [D] còn trong dáng ngồi [Em]\n"
            + "Thiên đường xưa khép lại [C]....... từ muôn [D] năm rồi [G]\n"
            + "Thiên đường đã khép nguồn cơn [C]\n"
            + "Từ hôm [D] dòng sông rũ mình [Em]\n"
            + "Quên được không những điều.[C]... đã [D] bao giờ qua [G]\n"
            + "Quên được mỗi sáng mùa đông [C]\n"
            + "Nhìn ra [D] ngày sương giá mềm [Em]\n"
            + "Quên được không những điều [C] ta chưa [D] bao giờ.[G]";
    public static String song3 = "Quê nhà tôi ơi [Am] , xứ Đoài xa vắng [Fmaj7] \n"
            + "Khói chiều mênh mông [Dm] , sông đã buông nắng [Bb] [Bm7b5] ....\n"
            + "Nhớ thương làng quê [E7], lũy tre, bờ đê [Fmaj7]\n"
            + "Ước mơ trở về [Bm7b5]nghe mẹ hiền ru bên thềm đá cũ [E7]\n"
            + "\n"
            + "Quê nhà tôi ơi [Am] con đường qua ngõ [Fmaj7]\n"
            + "Bóng Mẹ liêu xiêu [Dm] trong chiều buông gió [Bb] [Bm7b5]\n"
            + "Nhớ thương đàn con [E7] , biết phương trời nào [Fmaj7]\n"
            + "Áo nâu mùa Đông [Bm7b5] thương mình lận đận [E7]\n"
            + "Đêm buồn Mẹ ru [A]:\n"
            + "\n"
            + "\" à ơi [A]... hoa bay lên trời, cây Chi ở lại,[C#m]\n"
            + "à ơi [F#m]..... hoa cải lên trời,\n"
            + "Rau Răm ở lại [E7] chịu đời [Dm] đắng cay [A] \"\n"
            + "\n"
            + "Quê nhà tôi ơi[Am] , ba vì danh tí [Fmaj7]\n"
            + "Nón chiều che ngang [Dm]mặt trời hoang vắng [Bb] [Bm7b5]\n"
            + "Những đêm mùa Đông [E7] , khói hương trầm bay [Fmaj7]\n"
            + "Bóng Cha ngồi đây [Bm7b5] bức tường lung lay\n"
            + "Ngọn đèn vôi trắng [E7]....\n"
            + "\n"
            + "Quê nhà tôi ơi,[Am] quê người con gái [Fmaj7]\n"
            + "Mắt buồn, da nâu,[Dm] dấu tình yêu dấu [Bb] [Bm7b5]\n"
            + "Mắt đen về đâu,[E7] mắt đen của tôi [Fmaj7]\n"
            + "Mắt đen chờ ai [Bm7b5] tháng ngày mõi mệt [E7]\n"
            + "Ôi tình long đong [A]\n"
            + "\n"
            + "\"À ơi [A], em đi lấy chồng, anh vẫn một mình [C#m]\n"
            + "à ơi [F#m], táo rụng sân đình thương anh một mình [E7]\n"
            + "một mình [Dm] nhớ em [A]....\n"
            + "\n"
            + " à ơi [A]... hoa bay lên trời, cây Chi ở lại,[C#m]\n"
            + "à ơi [F#m]..... hoa cải lên trời,\n"
            + "Rau Răm ở lại [E7] chịu đời [Dm] đắng cay [A]\n"
            + " à ơi .. hoa cải bay đi [C#m], rau răm thôi đành[Dm] … thôi đành.[E7] .ở lại.[A]..";
    public static String song4 = "Hẹn hò mãi [Gmaj7] sao anh không về với [F#7] em \n"
            + "Ở nơi ấy [Bm] anh đang nghĩ gì [D7]\n"
            + "Có nhớ em [Gmaj7] hay anh đã quên,[F#7] làm em [Bm] bối rối.. \n"
            + "\n"
            + "Hẹn hò mãi [Gmaj7] sao anh vẫn còn bên [F#7] ấy \n"
            + "Để em cứ [Bm] ngóng trông cõi này [D7] \n"
            + "Chuyện là thế [Gmaj7] sao em lại khóc [F#7] bởi yêu anh mà [Bm]thôi.. \n"
            + "\n"
            + "Kìa [A] áng mây trời [D] bay [Gmaj7] bay [F#7] bay về xa mãi [Bm] \n"
            + "Kìa [A] dòng sông cứ [D] trôi [C#m7b5] về [Bm] nơi xa [Gmaj7] vời vợi, trôi mãi [C#m7b5]để rồi xa mãi[F#7]. \n"
            + "\n"
            + "Đã biết anh [Bm] như mây nhởn nhơ [E7] vẫn yêu như [G] ngày [A] xưa [D] \n"
            + "Đã biết anh [Bm] như sông chảy xuôi [E7] vẫn thương, thương [G] vậy [A] thôi [D] \n"
            + "Đã biết anh [Bm] như mây nhởn nhơ [E7] vẫn yêu như [G] ngày [A] xưa.[D] \n"
            + "Đã biết anh [Bm] như sông chảy xuôi [E7] vẫn thương, thương [G] vậy [A] thôi [D]";
    public static String song5 = "Gió [Gm] rét đang về, lê dài thêm [D7] kí ức khô cằn\n"
            + "Nhọc nhằn giọt nước [D#] mắt khẽ rơi\n"
            + "Nhọc nhằn khói [D7] thuốc trắng bay\n"
            + "Mùa đêm [Gm] rất mơ hồ, giấc mơ mùa lá [D7] trút năm nào\n"
            + "Kỉ niệm ngày xưa [D#] xa rất xa\n"
            + "Ngọt nhạt đầu môi [D7] dễ lãng quên\n"
            + "\n"
            + "Mùa lá [Gm] rớt trên vai, mùa se [Dm] lạnh\n"
            + "Mùa nắng [D#] tắt rất nhanh, mùa hoàng [D7] hôn đầy gió\n"
            + "Mùa muốn [Gm] sát bên nhau để ấm [Dm] hơn\n"
            + "Và mùa nơi đây chỉ gió [D#] tấp sau lưng \n"
            + "và nước [D7] mắt rơi dễ dàng[Gm] ...\n"
            + "\n"
            + "Mùa đi ngang phố [D#], hay phố [F] không mùa [Gm] nữa\n"
            + "Chỉ một vùng nỗi nhớ [D#] , ùa trên [F] phố rất vội [Gm]\n"
            + "Người mỉm cười nơi ngõ [D#] vắng\n"
            + "Bỏ quên [F] phía sau một mùa [D7]lá về trên [Gm] con [F] đường [D#]\n"
            + "Còn nguyên [F] nỗi xót xa [D7]\n"
            + "\n"
            + "Từng hàng cây nơi ngõ [D#] vắng như vẫy [F] tay vội vã [Gm]\n"
            + "Mùa đi mang theo lá [D#] úa phủ rơi [F] kín con đường[Gm]\n"
            + "Người giật mình nơi cuối [D#] phố\n"
            + "Gạt nước [F] mắt rơi nơi mùa [D7] đi ngang phố [Gm] năm [F#] nào [D#]\n"
            + "Rồi xa [F] rất xa như lá [D7] bay không về.[Gm]..";
}
